name: splitz
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_database: ^11.1.6
  flutter_native_splash: ^2.4.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  dio: ^5.7.0
  oauth2: ^2.0.3
  flutter_secure_storage: ^9.2.2
  webview_flutter: ^4.10.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  multi_thumb_slider: ^1.0.0
  another_xlider: ^3.0.2
  collection: ^1.18.0
  flutter_speed_dial: ^7.0.0
  currency_text_input_formatter: ^2.2.6
  flutter_svg: ^2.0.16
  gsheets: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.svg
